### ISSUE TITLE
Cannot read property 'length' or undefined

### ISSUE THREAD

**Issue by alduro** [cutting-room-floor/backbone-couch#1]
```
/*
 * Backbone - CouchBD connection
 */
 var connection = new cradle.Connection('http://localhost', 5984, {
   auth: { username: 'admin', password: 'XXXXXXX' }, 
   cache: true,
   raw: false
 });
 // Create a new backbone-couch handler for a database 'mercado'.
 var couch = require('backbone-couch')(connection, 'mercado');
 // Create database, push default design documents to it and
 // assign sync method to Backbone.
 couch.install(function(err) {
     Backbone.sync = couch('mercado').sync;
 });
```

/   Users/aldo/Satio/Desarrollo/express/mercado/lib/backbone-couch.js:29
                       'Content-Length': data.length,
                                             ^
T   ypeError: Cannot read property 'length' of undefined
       at /Users/aldo/Satio/Desarrollo/express/mercado/lib/backbone-couch.js:29:43
       at [object Object].<anonymous> (fs.js:80:5)
       at [object Object].emit (events.js:64:17)
       at fs.js:819:12

**Comment by alduro** [comment]
Forget it. I haven't installed base.json file under lib directory. An Installation how-to should be great ! thanks.
